### ISSUE TITLE
Positioning an Input directly beneath the location of a recent tap (<500ms) causes it to focus.

### ISSUE THREAD

**Issue by dgavey** [runspired/ember-mobiletouch#27] opened 2015-03-12 22:30 UTC
I don't have a simple test for you yet, but perhaps you have an idea for me anyway.  I have some tap events that when the route transitions and if there is an input or text area in the same physical area that was touched, then the input or textarea will gain focus. After the route has transitioned.

This happens on both Android and iOS.

Any thoughts?

**Comment by runspired** [comment] 2015-03-12 22:36
I'm going to need more data.  I suspect it's the "ghost click" mobile browsers fire off after touchEnd isn't getting cancelled properly, or that the fastfocus mechanism (which picks up on touchEnd) is involved.

Is this version 1.4.2?

I'm working on an ember-cli addon to produce globals builds of ember-addons, this one being the target project.  I'm hoping to land an alpha of that tonight, which would allow for jsbin reproduction of bug reports.  If I get it I'll provide a jsbin template that can be used for recreating this.

**Comment by dgavey** [comment] 2015-03-12 23:11
Yes 1.4.2 and that sounds like an interesting project. I'll watch for your updates. Thanks!

**Comment by dgavey** [comment] 2015-03-17 20:05
Introducing a delay of 200ms on tap, before the transition, seems to stop this behaviour from happening.

**Comment by runspired** [comment] 2015-03-19 20:18
There's improved handling of busting ghost clicks in 1.4.8.

- The buster observes the app's rootElement now instead document, ensuring that all clicks that should be busted are caught.
- The buster is defined before other click handlers on the rootElement, giving it precedence to stopImmediatePropagation.

Could you let me know if this issue persists after upgrading.

**Comment by dgavey** [comment] 2015-03-19 20:25
Unfortunately the issue still exists with 1.4.8.

**Comment by dgavey** [comment] 2015-03-19 20:39
Getting an error in 1.4.8 as well,might be related.

TypeError: undefined is not an object (evaluating 'ev.touches.length') is_mobile.js:63

**Comment by runspired** [comment] 2015-03-19 20:40
Definitely related, I'm almost done writing up a specific test for this issue, but that might be all that's needed.

**Comment by runspired** [comment] 2015-03-20 00:35
I was able to generate a test for this issue and tracked down both the undefined error and the root cause of the buster not busting all of the clicks.   Could you check out 1.4.9?

**Comment by dgavey** [comment] 2015-03-20 01:22
No more error, but unfortunately it still fires the click event after the transition.  I'll try and get a simple test case for you to try.

**Comment by dgavey** [comment] 2015-03-20 01:25
To be clear, it only fires the click event if there is some sort of input or text area on the next screen in the same area where I clicked on the previous screen to start the transition. Basically that input or textbox will gain focus.  It does not trigger other actions or links or anything else interactive.

**Comment by runspired** [comment] 2015-03-20 01:47
@dgavey are you sure you don't have some sort of autofocus on?  The test I added for this specifically swaps out an input where the tap took place and triggers the ghost click on the input.  Given how mobile environments have cases where human input is a necessity for an event to be fired, this could be untestable (automatically), but at least from a "detecting the click was properly cancelled"  perspective it should be.

**Comment by dgavey** [comment] 2015-03-20 01:48
Yeah, I'm sure.  We are using a lot of helping libraries though. It's possible one of them are interfering.  I'm gonna work on pairing the example down so I can figure it out.  Thanks for all your help!

**Comment by dgavey** [comment] 2015-03-20 01:57
Weird, ok I take it back.  It is working on my actual devices.  In my xcode simulators it still seems to be an issue. But as long as the devices aren't doing it. I'm very happy!

**Comment by dgavey** [comment] 2015-03-20 02:05
One more, update.  Android on chrome is perfect.  Safari on iOS is still an issue but not as bad as it used to be.  It doesn't trigger quite as often.

**Comment by runspired** [comment] 2015-03-20 03:11
I primarily test on Cordova iOS and haven't seen this issue there.  They aren't identical WebViews, but I'm curious what the difference here is.

**Comment by runspired** [comment] 2015-03-30 21:22
#33 shows that this is definitely an issue that affects any input that is moved into the position where the tap recently occurred.

**Comment by runspired** [comment] 2015-04-19 01:58
@dgavey Are you in the ember slack? ember-community-slackin.herokuapp.com

I'm working on this issue currently, as well as implementing a robust drag-and-drop api which I know you'd requested before.

**Comment by runspired** [comment] 2015-08-14 16:55
Closing as a won't fix edge case.  This is likely fixed by the use of a different approach for fastclick in ember-gestures.

**Closed by runspired** 2015-08-14 16:55 UTC
Labels: bug, in progress
